version: "3.9"

services:
  test-db:
    image: mysql
    restart: always
    container_name: integration-tests-prisma
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  dev-db:
    image: mysql
    restart: always
    container_name: development
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: taste-explorer
    ports:
      - "3307:3306"
