name: Check Code Formatting
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - "**"
  workflow_dispatch: # allow running in github actions manually
jobs:
  check-formatting:
    runs-on: ubuntu-20.04
    steps:
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: NPM Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci
      - name: Check Format
        working-directory: ./
        run: npx prettier --check .
      - name: Fail On Warnings
        run: |
          if [ $? -eq 0 ]; then
            echo "No formatting issues found"
          else
            echo "Formatting issues found. Run 'npx prettier --write .' to fix them."
            exit 1
          fi
