openapi: "3.0.0"
info:
  version: 1.0.0
  title: Music Taste Explorer
  description: >-
    "Create playlists to explore users's musical taste differences and similarities."
  termsOfService: adambechtold.xyz
  contact:
    name: Adam Bechtold
servers:
  - url: http://localhost:4000
tags:
  - name: users
    description: Operations related to users.
  - name: music
    description: Operations related to music.
paths:
  /api/users/{userId}:
    get:
      summary: Get User by Id
      description: Get a user by their id
      operationId: getUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          description: The id of the user to retrieve
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/music/playlists:
    get:
      summary: Get Playlist
      description: Get a playlist based on the users and the preference type
      operationId: getPlaylist
      tags:
        - music
      parameters:
        - name: userId1
          in: query
          description: The id of the first user
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
        - name: userId2
          in: query
          description: The id of the second user
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
        - name: preferenceType
          in: query
          description: The type of preference to use when creating the playlist
          required: true
          schema:
            type: string
            enum:
              - "USER1-ONLY"
              - "USER2-ONLY"
              - "BOTH"
      responses:
        "200":
          description: A list of tracks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Playlist"
  /api/music/lastfm-listens/{id}/track:
    get:
      summary: Get the Track from last.fm Listen
      description: Get the track information the last.fm listen
      operationId: getTrackFromLastfmListen
      tags:
        - music
      parameters:
        - name: Id
          in: path
          description: The id of the last.fm listen
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A track object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: last.fm Listen not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        lastfmAccount:
          $ref: "#/components/schemas/LastfmAccount"
    LastfmAccount:
      type: object
      required:
        - username
        - registeredAt
        - url
        - playCount
        - trackCount
      properties:
        username:
          type: string
        registeredAt:
          type: string
          format: date-time
        url:
          type: string
          format: uri
        playCount:
          type: integer
        trackCount:
          type: integer
    Playlist:
      type: object
      required:
        - tracks
      properties:
        tracks:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Track"
    Track:
      type: object
      required:
        - name
        - artists
      properties:
        name:
          type: string
        artists:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        spotifyId:
          type: string
    UserId:
      type: integer
      minimum: 1
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
